language: python

matrix:
  include:
    - os: linux
      python: 3.5.3
    - os: linux
      python: 3.6.2
    - os: linux
      python: 3.7.1
      # travis issue with Python 3.7 https://github.com/travis-ci/travis-ci/issues/9069
      dist: xenial
      sudo: required

install:
- pip install -U setuptools
- python setup.py install

before_script:
- | # decrypt credentials used in tests
  if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_d17283647768_key -iv $encrypted_d17283647768_iv -in test.synapseConfig.enc -out test.synapseConfig -d
    mv test.synapseConfig ~/.synapseConfig
  fi

script:
- pytest tests/unit
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ];then
    pytest tests/integration
  else
    echo "Skipping integration tests";
  fi
